### ISSUE TITLE
Doesn't run gpt reference?

### ISSUE THREAD

**Issue by YuchengWang** [hpcaitech/EnergonAI#196]
root@2d8fec1401d1:/workspace/EnergonAI# python examples/gpt/gpt_batch_server.py 
Traceback (most recent call last):
  File "/workspace/EnergonAI/examples/gpt/gpt_batch_server.py", line 7, in <module>
    from energonai.engine import InferenceEngine
ImportError: cannot import name 'InferenceEngine' from 'energonai.engine' (/opt/conda/lib/python3.9/site-packages/energonai/engine.py)

When I modified inferenceEngine. Another error ocurres:

root@2d8fec1401d1:/mnt/EnergonAI# python examples/gpt/gpt_batch_server.py 
Traceback (most recent call last):
  File "/mnt/EnergonAI/examples/gpt/gpt_batch_server.py", line 8, in <module>
    from energonai.legacy_batch_mgr.dynamic_batch_manager import Dynamic_Batch_Manager
  File "/opt/conda/lib/python3.9/site-packages/energonai/legacy_batch_mgr/__init__.py", line 1, in <module>
    from .worker_server import launch_worker
ModuleNotFoundError: No module named 'energonai.legacy_batch_mgr.worker_server'

**Comment by ver217** [comment]
Hi, please see https://github.com/hpcaitech/EnergonAI/tree/main/examples/bloom or https://github.com/hpcaitech/EnergonAI/tree/main/examples/opt and simply replace the model with GPT.
